"""baseline_schema

Revision ID: 5cd65d550812
Revises: 
Create Date: 2026-04-14 02:49:26.228184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd65d550812'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.Enum('SCHOOL', 'HOSPITAL', 'BUSINESS', 'HYBRID', name='industrytype'), nullable=False),
    sa.Column('subscription_tier', sa.Enum('FREE', 'STARTER', 'GROWTH', 'ENTERPRISE', name='subscriptiontier'), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('modules_enabled', sa.JSON(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_expires_at', sa.String(length=50), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('inventory_items',
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('quantity_in_stock', sa.Float(), nullable=True),
    sa.Column('reorder_level', sa.Float(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_inventory_items_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_items'))
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_sku'), ['sku'], unique=False)

    op.create_table('patients',
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('blood_type', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', 'UNKNOWN', name='bloodtype'), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('chronic_conditions', sa.JSON(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('insurance_provider', sa.String(length=255), nullable=True),
    sa.Column('insurance_policy_no', sa.String(length=100), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_patients_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_patient_id'), ['patient_id'], unique=False)

    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_roles_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_org_id'), ['org_id'], unique=False)

    op.create_table('tuckshop_products',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_tuckshop_products_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tuckshop_products'))
    )
    with op.batch_alter_table('tuckshop_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tuckshop_products_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tuckshop_products_org_id'), ['org_id'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('employee_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING', 'LOCKED', name='userstatus'), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('failed_login_attempts', sa.String(length=10), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invite_token', sa.String(length=255), nullable=True),
    sa.Column('invite_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_users_invited_by_users')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_users_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    op.create_table('appointments',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointmentstatus'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('fk_appointments_doctor_id_users')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_appointments_org_id_organizations')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_appointments_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_appointment_date'), ['appointment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_patient_id'), ['patient_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'LOGIN_FAILED', 'PASSWORD_RESET', 'MFA_ENABLED', 'USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'USER_SUSPENDED', 'USER_INVITED', 'ROLE_CHANGED', 'ORG_UPDATED', 'MODULE_ENABLED', 'MODULE_DISABLED', 'RECORD_CREATED', 'RECORD_UPDATED', 'RECORD_DELETED', 'DATA_EXPORTED', 'DATA_IMPORTED', name='auditaction'), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('resource_label', sa.String(length=255), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('actor_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_audit_logs_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)

    op.create_table('clubs',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('advisor_id', sa.String(length=36), nullable=True),
    sa.Column('meeting_day', sa.String(length=20), nullable=True),
    sa.Column('meeting_time', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['users.id'], name=op.f('fk_clubs_advisor_id_users')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_clubs_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clubs'))
    )
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clubs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clubs_org_id'), ['org_id'], unique=False)

    op.create_table('employees',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN', name='employmenttype'), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('manager_id', sa.String(length=36), nullable=True),
    sa.Column('base_salary', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('pay_frequency', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bank_account_no', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('pension_id', sa.String(length=50), nullable=True),
    sa.Column('nhf_id', sa.String(length=50), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_employees_manager_id_users')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_employees_org_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_employees_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees'))
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_employee_code'), ['employee_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_user_id'), ['user_id'], unique=True)

    op.create_table('import_jobs',
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'COMPLETED', 'PARTIALLY_COMPLETED', 'FAILED', 'ROLLED_BACK', name='importstatus'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('valid_rows', sa.Integer(), nullable=True),
    sa.Column('created', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Integer(), nullable=True),
    sa.Column('skipped_invalid', sa.Integer(), nullable=True),
    sa.Column('skipped_duplicate', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_ids', sa.JSON(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_email', sa.String(length=320), nullable=True),
    sa.Column('duplicate_strategy', sa.String(length=20), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_import_jobs_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_import_jobs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_jobs'))
    )
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_jobs_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('school_classes',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('teacher_id', sa.String(length=36), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_school_classes_org_id_organizations')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_school_classes_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_classes'))
    )
    with op.batch_alter_table('school_classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_classes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_classes_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_classes_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index('ix_school_classes_teacher_org', ['teacher_id', 'org_id'], unique=False)

    op.create_table('subjects',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('teacher_id', sa.String(length=36), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_subjects_org_id_organizations')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_subjects_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects'))
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index('ix_subjects_teacher_org', ['teacher_id', 'org_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('assignments',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_points', sa.Float(), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CLOSED', name='assignmentstatus'), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], name=op.f('fk_assignments_class_id_school_classes')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_assignments_org_id_organizations')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_assignments_subject_id_subjects')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_assignments_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments'))
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('cbt_exams',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('class_id', sa.String(length=36), nullable=True),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Float(), nullable=True),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ACTIVE', 'CLOSED', name='examstatus'), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], name=op.f('fk_cbt_exams_class_id_school_classes')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_cbt_exams_created_by_users')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_cbt_exams_org_id_organizations')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_cbt_exams_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cbt_exams'))
    )
    with op.batch_alter_table('cbt_exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cbt_exams_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cbt_exams_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cbt_exams_org_id'), ['org_id'], unique=False)

    op.create_table('finance_transactions',
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', 'TRANSFER', 'REFUND', name='transactiontype'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('counterparty', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('related_invoice_id', sa.String(length=36), nullable=True),
    sa.Column('related_employee_id', sa.String(length=36), nullable=True),
    sa.Column('import_job_id', sa.String(length=36), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], name=op.f('fk_finance_transactions_import_job_id_import_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_finance_transactions_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_transactions'))
    )
    with op.batch_alter_table('finance_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_transactions_import_job_id'), ['import_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_transactions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_transactions_reference'), ['reference'], unique=False)

    op.create_table('leave_requests',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leavestatus'), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_leave_requests_employee_id_employees')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_leave_requests_org_id_organizations')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_leave_requests_reviewed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_requests'))
    )
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_requests_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_org_id'), ['org_id'], unique=False)

    op.create_table('medical_invoices',
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PAID', 'OVERDUE', 'CANCELLED', name='invoicestatus'), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_medical_invoices_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_medical_invoices_org_id_organizations')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_medical_invoices_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_invoices'))
    )
    with op.batch_alter_table('medical_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_invoices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_invoices_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_invoices_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_invoices_patient_id'), ['patient_id'], unique=False)

    op.create_table('medical_records',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=True),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('icd_codes', sa.JSON(), nullable=True),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('prescriptions', sa.JSON(), nullable=True),
    sa.Column('lab_results', sa.JSON(), nullable=True),
    sa.Column('vitals', sa.JSON(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('is_confidential', sa.Boolean(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_medical_records_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('fk_medical_records_doctor_id_users')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_medical_records_org_id_organizations')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_medical_records_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_records'))
    )
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_records_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_records_patient_id'), ['patient_id'], unique=False)

    op.create_table('payslips',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('pay_period_start', sa.Date(), nullable=False),
    sa.Column('pay_period_end', sa.Date(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'PAID', 'FAILED', name='payrollstatus'), nullable=True),
    sa.Column('basic_salary', sa.Float(), nullable=True),
    sa.Column('allowances', sa.JSON(), nullable=True),
    sa.Column('bonuses', sa.JSON(), nullable=True),
    sa.Column('gross_salary', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('pension', sa.Float(), nullable=True),
    sa.Column('nhf', sa.Float(), nullable=True),
    sa.Column('other_deductions', sa.JSON(), nullable=True),
    sa.Column('total_deductions', sa.Float(), nullable=True),
    sa.Column('net_salary', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_payslips_employee_id_employees')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_payslips_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payslips'))
    )
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payslips_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payslips_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payslips_org_id'), ['org_id'], unique=False)

    op.create_table('photo_journals',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('taken_date', sa.Date(), nullable=True),
    sa.Column('posted_by', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=True),
    sa.Column('club_id', sa.String(length=36), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], name=op.f('fk_photo_journals_class_id_school_classes')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_photo_journals_club_id_clubs')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_photo_journals_org_id_organizations')),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], name=op.f('fk_photo_journals_posted_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photo_journals'))
    )
    with op.batch_alter_table('photo_journals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photo_journals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photo_journals_org_id'), ['org_id'], unique=False)

    op.create_table('students',
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('class_id', sa.String(length=36), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('graduation_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('guardian_name', sa.String(length=255), nullable=True),
    sa.Column('guardian_phone', sa.String(length=50), nullable=True),
    sa.Column('guardian_email', sa.String(length=320), nullable=True),
    sa.Column('guardian_relationship', sa.String(length=50), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], name=op.f('fk_students_class_id_school_classes')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_students_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students'))
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_email'), ['email'], unique=False)
        batch_op.create_index('ix_students_email_org', ['email', 'org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_student_id'), ['student_id'], unique=False)

    op.create_table('timetables',
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('teacher_id', sa.String(length=36), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], name=op.f('fk_timetables_class_id_school_classes')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_timetables_org_id_organizations')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_timetables_subject_id_subjects')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_timetables_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timetables'))
    )
    with op.batch_alter_table('timetables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timetables_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timetables_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timetables_org_id'), ['org_id'], unique=False)

    op.create_table('assignment_submissions',
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('graded_by', sa.String(length=36), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'GRADED', 'RETURNED', name='submissionstatus'), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name=op.f('fk_assignment_submissions_assignment_id_assignments')),
    sa.ForeignKeyConstraint(['graded_by'], ['users.id'], name=op.f('fk_assignment_submissions_graded_by_users')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_assignment_submissions_org_id_organizations')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_assignment_submissions_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignment_submissions'))
    )
    with op.batch_alter_table('assignment_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_submissions_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_submissions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_submissions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_submissions_student_id'), ['student_id'], unique=False)

    op.create_table('attendance_records',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='attendancestatus'), nullable=False),
    sa.Column('marked_by', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], name=op.f('fk_attendance_records_class_id_school_classes')),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], name=op.f('fk_attendance_records_marked_by_users')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_attendance_records_org_id_organizations')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_attendance_records_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records'))
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_records_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_student_id'), ['student_id'], unique=False)

    op.create_table('behaviour_records',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('recorded_by', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', name='behaviourtype'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_behaviour_records_org_id_organizations')),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_behaviour_records_recorded_by_users')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_behaviour_records_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_behaviour_records'))
    )
    with op.batch_alter_table('behaviour_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_behaviour_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_behaviour_records_incident_date'), ['incident_date'], unique=False)
        batch_op.create_index('ix_behaviour_records_org_date', ['org_id', 'incident_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_behaviour_records_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_behaviour_records_student_id'), ['student_id'], unique=False)

    op.create_table('cbt_attempts',
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUBMITTED', 'GRADED', name='attemptstatus'), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['cbt_exams.id'], name=op.f('fk_cbt_attempts_exam_id_cbt_exams')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_cbt_attempts_org_id_organizations')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_cbt_attempts_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cbt_attempts'))
    )
    with op.batch_alter_table('cbt_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cbt_attempts_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cbt_attempts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cbt_attempts_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cbt_attempts_student_id'), ['student_id'], unique=False)

    op.create_table('cbt_questions',
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('MCQ', 'TRUE_FALSE', 'SHORT_ANSWER', 'LONG_ANSWER', name='questiontype'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['cbt_exams.id'], name=op.f('fk_cbt_questions_exam_id_cbt_exams')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_cbt_questions_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cbt_questions'))
    )
    with op.batch_alter_table('cbt_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cbt_questions_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cbt_questions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cbt_questions_org_id'), ['org_id'], unique=False)

    op.create_table('club_memberships',
    sa.Column('club_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_memberships_club_id_clubs')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_club_memberships_org_id_organizations')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_club_memberships_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_memberships'))
    )
    with op.batch_alter_table('club_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_club_memberships_club_id'), ['club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_club_memberships_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_club_memberships_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_club_memberships_student_id'), ['student_id'], unique=False)

    op.create_table('grades',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('term', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('grade_letter', sa.String(length=5), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='gradestatus'), nullable=True),
    sa.Column('graded_by', sa.String(length=36), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['graded_by'], ['users.id'], name=op.f('fk_grades_graded_by_users')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_grades_org_id_organizations')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_grades_student_id_students')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_grades_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grades'))
    )
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grades_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grades_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grades_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grades_subject_id'), ['subject_id'], unique=False)

    op.create_table('student_feedback',
    sa.Column('submitted_by', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('GENERAL', 'FACILITIES', 'TEACHING', 'BULLYING', 'SUGGESTION', 'OTHER', name='feedbackcategory'), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('responded_by', sa.String(length=36), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_student_feedback_org_id_organizations')),
    sa.ForeignKeyConstraint(['responded_by'], ['users.id'], name=op.f('fk_student_feedback_responded_by_users')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_feedback_student_id_students')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_student_feedback_submitted_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_feedback'))
    )
    with op.batch_alter_table('student_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_feedback_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_feedback_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_feedback_submitted_by'), ['submitted_by'], unique=False)

    op.create_table('tuckshop_purchases',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('sold_by', sa.String(length=36), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_tuckshop_purchases_org_id_organizations')),
    sa.ForeignKeyConstraint(['product_id'], ['tuckshop_products.id'], name=op.f('fk_tuckshop_purchases_product_id_tuckshop_products')),
    sa.ForeignKeyConstraint(['sold_by'], ['users.id'], name=op.f('fk_tuckshop_purchases_sold_by_users')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_tuckshop_purchases_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tuckshop_purchases'))
    )
    with op.batch_alter_table('tuckshop_purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tuckshop_purchases_id'), ['id'], unique=False)
        batch_op.create_index('ix_tuckshop_purchases_org_created', ['org_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tuckshop_purchases_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tuckshop_purchases_student_id'), ['student_id'], unique=False)

    op.create_table('weekly_reflections',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mood', sa.String(length=30), nullable=True),
    sa.Column('teacher_comment', sa.Text(), nullable=True),
    sa.Column('commented_by', sa.String(length=36), nullable=True),
    sa.Column('commented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['commented_by'], ['users.id'], name=op.f('fk_weekly_reflections_commented_by_users')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_weekly_reflections_org_id_organizations')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_weekly_reflections_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_reflections'))
    )
    with op.batch_alter_table('weekly_reflections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_reflections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_reflections_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_reflections_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_reflections_week_start'), ['week_start'], unique=False)

    op.create_table('weekly_remarks',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('areas_to_improve', sa.Text(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_weekly_remarks_org_id_organizations')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_weekly_remarks_student_id_students')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_weekly_remarks_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_remarks'))
    )
    with op.batch_alter_table('weekly_remarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_remarks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_remarks_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_remarks_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_remarks_week_start'), ['week_start'], unique=False)

    op.create_table('cbt_answers',
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('points_awarded', sa.Float(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['cbt_attempts.id'], name=op.f('fk_cbt_answers_attempt_id_cbt_attempts')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_cbt_answers_org_id_organizations')),
    sa.ForeignKeyConstraint(['question_id'], ['cbt_questions.id'], name=op.f('fk_cbt_answers_question_id_cbt_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cbt_answers'))
    )
    with op.batch_alter_table('cbt_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cbt_answers_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cbt_answers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cbt_answers_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cbt_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cbt_answers_org_id'))
        batch_op.drop_index(batch_op.f('ix_cbt_answers_id'))
        batch_op.drop_index(batch_op.f('ix_cbt_answers_attempt_id'))

    op.drop_table('cbt_answers')
    with op.batch_alter_table('weekly_remarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_remarks_week_start'))
        batch_op.drop_index(batch_op.f('ix_weekly_remarks_student_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_remarks_org_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_remarks_id'))

    op.drop_table('weekly_remarks')
    with op.batch_alter_table('weekly_reflections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_reflections_week_start'))
        batch_op.drop_index(batch_op.f('ix_weekly_reflections_student_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_reflections_org_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_reflections_id'))

    op.drop_table('weekly_reflections')
    with op.batch_alter_table('tuckshop_purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tuckshop_purchases_student_id'))
        batch_op.drop_index(batch_op.f('ix_tuckshop_purchases_org_id'))
        batch_op.drop_index('ix_tuckshop_purchases_org_created')
        batch_op.drop_index(batch_op.f('ix_tuckshop_purchases_id'))

    op.drop_table('tuckshop_purchases')
    with op.batch_alter_table('student_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_feedback_submitted_by'))
        batch_op.drop_index(batch_op.f('ix_student_feedback_org_id'))
        batch_op.drop_index(batch_op.f('ix_student_feedback_id'))

    op.drop_table('student_feedback')
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grades_subject_id'))
        batch_op.drop_index(batch_op.f('ix_grades_student_id'))
        batch_op.drop_index(batch_op.f('ix_grades_org_id'))
        batch_op.drop_index(batch_op.f('ix_grades_id'))

    op.drop_table('grades')
    with op.batch_alter_table('club_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_club_memberships_student_id'))
        batch_op.drop_index(batch_op.f('ix_club_memberships_org_id'))
        batch_op.drop_index(batch_op.f('ix_club_memberships_id'))
        batch_op.drop_index(batch_op.f('ix_club_memberships_club_id'))

    op.drop_table('club_memberships')
    with op.batch_alter_table('cbt_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cbt_questions_org_id'))
        batch_op.drop_index(batch_op.f('ix_cbt_questions_id'))
        batch_op.drop_index(batch_op.f('ix_cbt_questions_exam_id'))

    op.drop_table('cbt_questions')
    with op.batch_alter_table('cbt_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cbt_attempts_student_id'))
        batch_op.drop_index(batch_op.f('ix_cbt_attempts_org_id'))
        batch_op.drop_index(batch_op.f('ix_cbt_attempts_id'))
        batch_op.drop_index(batch_op.f('ix_cbt_attempts_exam_id'))

    op.drop_table('cbt_attempts')
    with op.batch_alter_table('behaviour_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_behaviour_records_student_id'))
        batch_op.drop_index(batch_op.f('ix_behaviour_records_org_id'))
        batch_op.drop_index('ix_behaviour_records_org_date')
        batch_op.drop_index(batch_op.f('ix_behaviour_records_incident_date'))
        batch_op.drop_index(batch_op.f('ix_behaviour_records_id'))

    op.drop_table('behaviour_records')
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_student_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_org_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_date'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_class_id'))

    op.drop_table('attendance_records')
    with op.batch_alter_table('assignment_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_submissions_student_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_submissions_org_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_submissions_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_submissions_assignment_id'))

    op.drop_table('assignment_submissions')
    with op.batch_alter_table('timetables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timetables_org_id'))
        batch_op.drop_index(batch_op.f('ix_timetables_id'))
        batch_op.drop_index(batch_op.f('ix_timetables_class_id'))

    op.drop_table('timetables')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_student_id'))
        batch_op.drop_index(batch_op.f('ix_students_org_id'))
        batch_op.drop_index(batch_op.f('ix_students_id'))
        batch_op.drop_index('ix_students_email_org')
        batch_op.drop_index(batch_op.f('ix_students_email'))

    op.drop_table('students')
    with op.batch_alter_table('photo_journals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photo_journals_org_id'))
        batch_op.drop_index(batch_op.f('ix_photo_journals_id'))

    op.drop_table('photo_journals')
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payslips_org_id'))
        batch_op.drop_index(batch_op.f('ix_payslips_id'))
        batch_op.drop_index(batch_op.f('ix_payslips_employee_id'))

    op.drop_table('payslips')
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_records_patient_id'))
        batch_op.drop_index(batch_op.f('ix_medical_records_org_id'))
        batch_op.drop_index(batch_op.f('ix_medical_records_id'))

    op.drop_table('medical_records')
    with op.batch_alter_table('medical_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_invoices_patient_id'))
        batch_op.drop_index(batch_op.f('ix_medical_invoices_org_id'))
        batch_op.drop_index(batch_op.f('ix_medical_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_medical_invoices_id'))

    op.drop_table('medical_invoices')
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_requests_org_id'))
        batch_op.drop_index(batch_op.f('ix_leave_requests_id'))
        batch_op.drop_index(batch_op.f('ix_leave_requests_employee_id'))

    op.drop_table('leave_requests')
    with op.batch_alter_table('finance_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_transactions_reference'))
        batch_op.drop_index(batch_op.f('ix_finance_transactions_org_id'))
        batch_op.drop_index(batch_op.f('ix_finance_transactions_import_job_id'))
        batch_op.drop_index(batch_op.f('ix_finance_transactions_id'))

    op.drop_table('finance_transactions')
    with op.batch_alter_table('cbt_exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cbt_exams_org_id'))
        batch_op.drop_index(batch_op.f('ix_cbt_exams_id'))
        batch_op.drop_index(batch_op.f('ix_cbt_exams_class_id'))

    op.drop_table('cbt_exams')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_org_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_class_id'))

    op.drop_table('assignments')
    op.drop_table('user_roles')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index('ix_subjects_teacher_org')
        batch_op.drop_index(batch_op.f('ix_subjects_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_subjects_org_id'))
        batch_op.drop_index(batch_op.f('ix_subjects_id'))

    op.drop_table('subjects')
    with op.batch_alter_table('school_classes', schema=None) as batch_op:
        batch_op.drop_index('ix_school_classes_teacher_org')
        batch_op.drop_index(batch_op.f('ix_school_classes_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_school_classes_org_id'))
        batch_op.drop_index(batch_op.f('ix_school_classes_id'))

    op.drop_table('school_classes')
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_import_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_import_jobs_org_id'))
        batch_op.drop_index(batch_op.f('ix_import_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_import_jobs_entity'))

    op.drop_table('import_jobs')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_user_id'))
        batch_op.drop_index(batch_op.f('ix_employees_org_id'))
        batch_op.drop_index(batch_op.f('ix_employees_id'))
        batch_op.drop_index(batch_op.f('ix_employees_employee_code'))

    op.drop_table('employees')
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clubs_org_id'))
        batch_op.drop_index(batch_op.f('ix_clubs_id'))

    op.drop_table('clubs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_org_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_org_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_appointment_date'))

    op.drop_table('appointments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_org_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tuckshop_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tuckshop_products_org_id'))
        batch_op.drop_index(batch_op.f('ix_tuckshop_products_id'))

    op.drop_table('tuckshop_products')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_org_id'))
        batch_op.drop_index(batch_op.f('ix_roles_id'))

    op.drop_table('roles')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patients_org_id'))
        batch_op.drop_index(batch_op.f('ix_patients_id'))

    op.drop_table('patients')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_sku'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_org_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_id'))

    op.drop_table('inventory_items')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.drop_index(batch_op.f('ix_organizations_id'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
